services:
  app:
    image: ${DOCKER_USERNAME:-dortune10}/church-app:latest
    container_name: church-app
    restart: always
    ports:
      - "3330:3330"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
